### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by debjyoti197** [kinestetika/Calisp#1]
I am trying to analyze an mzML file for Deuterium using Calisp. However, I'm getting an error like this:

Traceback (most recent call last):
  File "/home/ghoshd/miniconda3/envs/calisp/bin/calisp", line 8, in <module>
    sys.exit(main())
  File "/home/ghoshd/miniconda3/envs/calisp/lib/python3.10/site-packages/calisp/main.py", line 355, in main
    f'reassigned {patterns_reassigned_count / len(pattern_data.index) * 100:.1f}% of patterns to '
ZeroDivisionError: division by zero

It would be great to know why this error is coming up and if you have any suggestions on how to avoid this.

**Comment by kinestetika** [comment]
Hi Dbjyoti197.

Last year, calisp was ported to python, and I stopped maintaining the old java version. I'll add a note to the readme. You can find the new version here:

https://github.com/kinestetika/Calisp

I would recommend to use the python version. Especially if you're using Deuterium data, I would expect the python version to work better.

**Comment by debjyoti197** [comment]
Hi kinestetika,

I have been getting this error using the python version (calisp 3.0.9). 
It would be good to know if there's any reason behind the error.

**Comment by kinestetika** [comment]
Ok hold on I'll get back to you...

**Comment by kinestetika** [comment]
Hi Debjyoti,

Sorry about the delay.
Can you send me the complete output of calisp that led up to this error?
Thanks!

Marc

**Comment by debjyoti197** [comment]
Hi Marc,

Thanks for the reply.
I have pasted herewith a screenshot that would show the error messages.
[image: Calisp_output_error_message.png]

Wish you a nice day.

Best regards,
Debjyoti

**Comment by kinestetika** [comment]
Hi Debjyoti,

can you send that screenshot again, it was not attached your message...

Thanks!
Marc

**Comment by debjyoti197** [comment]
Sorry for the inconvenience. I am attaching it herewith.

Hope to hear from you soon.

Best regards,
Debjyoti

**Comment by kinestetika** [comment]
Hi Debjyoti,

still no attachment...

It would work better for me if you send your messages to my work email (
***@***.***) - I don't check this address that often...

Best!
Marc
