### ISSUE TITLE
Include license file in pypi distribution

### ISSUE THREAD

**Issue by bernt-matthias** [kinestetika/Calisp#3]
Guess this would be a nice thing to do. Just noticed while preparing a `(bio)conda recipe for calisp: https://github.com/bioconda/bioconda-recipes/pull/39720

**Comment by kinestetika** [comment]
Hi bernt-matthias, thanks for your comment I have updated the code to include LICENSE.txt in the PyPi distro, Marc

**Comment by bernt-matthias** [comment]
Thanks. Added it in the bioconda recipe https://github.com/bioconda/bioconda-recipes/pull/39773
