### ISSUE TITLE
Small test data

### ISSUE THREAD

**Issue by bernt-matthias** [kinestetika/Calisp#4]
While working on a wrapper for Galaxy I was wondering if there is a small test data set for calisp. 

Ideally it would be possible to run calisp as short time as possible .. and size of max 1MB would be cool.

**Comment by kinestetika** [comment]
Hi Bernt, I've created a small dataset for testing. Unfortunately it is still about 14 Mb large (that is still  at least 100x smaller than data for a typical MS run). The calisp run is quite fast, about 2 s on my 10 year old laptop. I've added the two input files to the repository, as well as the output that should be expected if calisp is running well. Is this something that could work for you? Would you want those files to be included in a calisp installation? If yes, I'll update setup.py. Let me know...

**Comment by bernt-matthias** [comment]
Dear @kinestetika. This sounds great. 

> Would you want those files to be included in a calisp installation?

I think this is not necessary.
