### ISSUE TITLE
Traceback

### ISSUE THREAD

**Issue by bernt-matthias** [kinestetika/Calisp#5]
On my quest for [small test](https://github.com/kinestetika/Calisp/issues/4) data I created input that resulted in this:

```
Job in error state.. tool_id: calisp, exit_code: 1, stderr: Traceback (most recent call last):
  File "/home/berntm/miniconda3/envs/__calisp@3.0.10/bin/calisp", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/berntm/miniconda3/envs/__calisp@3.0.10/lib/python3.11/site-packages/calisp/main.py", line 336, in main
    psm_with_ms1_spectrum_count += set_precursor(ms2_spectra_precursors[
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/berntm/miniconda3/envs/__calisp@3.0.10/lib/python3.11/site-packages/calisp/main.py", line 105, in set_precursor
    my_psm_data.at[index, 'psm_precursor_id'] = int(precursor_dict['precursor id'])
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

Any idea what I could have none wrong?

**Comment by bernt-matthias** [comment]
OK .. with picked MS1-Level I get: 

`No patterns found, no output will be created for this spectrum file. This is unusual. This maybe caused by a problem with the Calisp code or with the peptide file format.`

**Comment by kinestetika** [comment]
Hi Bernt, thanks for your message. I'm planning to create and share these small test files in this repository but have not yet managed to find time to create them. Editing mzml files is tricky because they contain a mixture of html and binary encoded data so I will need to carefully write a script to do this. I should manage before June 1.

**Comment by bernt-matthias** [comment]
Excellent. Thanks for letting me know.

**Comment by kinestetika** [comment]
Test data has been created and added to the repository
